# Generated by Django 6.0.1 on 2026-01-18 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='dependency_uploads/')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('total_dependencies', models.IntegerField(default=0)),
                ('vulnerabilities_found', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('cve_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('remediation', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='dependency_analysis.scanreport')),
            ],
        ),
    ]
