# Generated by Django 6.0.1 on 2026-01-31 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanreport',
            name='uploaded_file',
        ),
        migrations.CreateModel(
            name='DependencyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_files', to='dependency_analysis.scanreport')),
            ],
        ),
    ]
