# Generated by Django 6.0.1 on 2026-03-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposedport',
            name='scanStatus',
            field=models.CharField(default='Unknown Error'),
        ),
        migrations.AlterField(
            model_name='exposedport',
            name='is_risk',
            field=models.BooleanField(default='Unevaluated'),
        ),
    ]
