# Generated by Django 6.0.1 on 2026-03-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_monitor', '0003_exposedport_exploit_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposedport',
            name='is_risk',
            field=models.CharField(default='Unevaluated'),
        ),
    ]
